%% script to calculate other quantities from eps_x and eps_y

for i = 1:plottingData(1).nFiles
    
    % principal strains
    [plottingData(i).strain_xx_princ,...
       plottingData(i).strain_yy_princ,... 
       plottingData(i).principalAngle_t,...
       plottingData(i).principalAngle_c] = principalValues(plottingData(i).strains_xx,...
                                                   plottingData(i).strains_yy,...
                                                   plottingData(i).strains_xy);
                                               
    plottingData(i).principalStrain_max = max(plottingData(i).strain_xx_princ, plottingData(i).strain_yy_princ);
    plottingData(i).principalStrain_min = min(plottingData(i).strain_xx_princ, plottingData(i).strain_yy_princ);
    
    [plottingData(i).hydrostaticStrain,...
        plottingData(i).deviatoricStrain] = volumetricAndDeviatoric(plottingData(i).strains_xx,...
                                                   plottingData(i).strains_yy,...
                                                   plottingData(i).strains_xy);
    
end